# Generated by Django 3.0.5 on 2020-04-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
    ]
